# Generated by Django 4.0.2 on 2022-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor', models.CharField(max_length=200)),
                ('co2_emission', models.FloatField(default=1, unique=None)),
            ],
        ),
    ]
